name: 04 - Using Actions

on: push

jobs:
    build:
        runs-on: ubuntu-latest        
        steps:
          - name: Checkout Code
            uses: actions/checkout@v4
          - name: Printing Folders
            uses: ls

        # 0. checar o codigo do nosso repositorio
        # 1. instalar as dependencias da nossa react application
        # 2. executar testes automaticos