name: 05 - 1 - Events filters and Activity Types

on: 
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - main

jobs:
    echo:
        runs-on: ubuntu-latest       
        steps:
          - run: echo "Running wherever a PR is opened or synchronized AND base branch is main"