name: 05 - 1 - Events filters and Activity Types

on: 
  pull_requests:
    types:
      - opened
      - syncronize
    branches:
      - main

jobs:
    echo:
        runs-on: ubuntu-latest       
        steps:
          - run: echo "Running wherever a PR is opened or syncronized AND base branch is main"